---
title: "p8105_hw1_mc5503.Rmd"
author: "mc5503"
date: "2023-09-18"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(moderndive)
library(tidyverse)
data("early_january_weather")
```
# Problem 1
### discribe the dataset
```{r}
early_january_weather
nrow(early_january_weather)
ncol(early_january_weather)
mean(early_january_weather$temp)
```

### make plots
```{r}
plot_p1=ggplot(early_january_weather,
       aes(x = time_hour,
           y = temp,
           color=humid)) + geom_point()
plot_p1
ggsave("plot_p1.png",plot_p1)
```

# Problem 2
### create one dataframe and take the mean.
```{r, warning=FALSE}
# create the dataframe
df_p2=tibble(
  vec_numeric=rnorm(10),
  vec_logical=vec_numeric>0,
  vec_char=c('qw','er','ty','ui','op','as','df','gh','jk','lz'),
  vec_factor=factor(c('A','B','C','C','C','B','A','A','C','B'))
)
df_p2
# pull the variables
vec_numeric=pull(df_p2,vec_numeric)
vec_logical=pull(df_p2,vec_logical)
vec_char=pull(df_p2,vec_char)
vec_factor=pull(df_p2,vec_factor)
# take the means of each variable
mean(vec_numeric)
mean(vec_logical)
mean(vec_char)
mean(vec_factor)
```

### convert variable types
```{r,results='hide',warning=FALSE}
as.numeric(vec_logical)
as.numeric(vec_char)
as.numeric(vec_factor)
```
Only logical and factor variables can be converted to numeric type. 
It's possible to take means only for the quantitative variables.